name: Initialize App Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: Release Type
        options: [ patch, minor, major ]
jobs:
  run:
    name: Prepare '${{ github.event.inputs.release_type }}' version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Prepare App for Release
        id: artifact
        uses: htec-infra/gha-utils/actions/init-release@6adb1c12dc43cc91275bbfb1ff3fe7a8bd79f296
        with:
          release_type: ${{ github.event.inputs.release_type }}
