name: Artifacts CI

on:
  pull_request:
    types: [ opened, synchronize, closed ]
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Global ENVs
jobs:
  build_and_publish:
    uses: ./.github/workflows/reuse.yaml
    with:
      rocm_release: ${{ github.event.inputs.rocm_release || '5.1' }}
      result_number: ${{ github.event.inputs.result_number || '10' }}
      flags: ${{ github.event.inputs.flags || '-s' }} 
      performance_reports_repo: ${{ github.event.inputs.performance_reports_repo || 'migraphx-benchmark/migraphx-reports' }} 
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
