name: Artifacts CI

on:
  pull_request:
    types: [ opened, synchronize, closed ]
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  
permissions:
  issues: write
  pull-requests: write
  contents: read
  id-token: write

# Global ENVs
jobs:
  build_and_publish:
    name: Get repository data
    runs-on: ubuntu-latest
#     outputs:
#       app_version: ${{ steps.repo_data.outputs.app_version }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-central-1
          role-to-assume: arn:aws:iam::336020864752:role/OrbitGitHubRunner
      - name: run
        run: aws s3 ls
#   auto_deploy:
#     name: Create GitHub Release
#     if: github.event.pull_request.merged == true  && contains(github.head_ref, 'release/')
#     needs: build_and_publish
#     runs-on: ubuntu-latest
#     steps:
#       - name: Run auto-deploy
#         uses: htec-infra/gha-utils/actions/repo-dispatch@feature/new-gh-release
#         with:
#           gh_token: ${{ secrets.CI_PAT }}
#           event_type: new_github_release
#           client_payload: '{"env": "dev", "version": "${{ needs.build_and_publish.outputs.app_version }}"}'
