name: Artifacts CI

on:
  # Triggers the workflow on push or pull request events but only for the main/master branch
#   push:
#     branches: [ main ]
#     paths:
#       - src/**
#       - infra/**
  pull_request:
    types: [ opened, synchronize, closed ]
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Global ENVs
env:
  APP_REVISION: ${{ github.event.pull_request.head.sha || github.sha }}
jobs:
  build_and_publish:
    name: Get repository data
    runs-on: ubuntu-latest
#     outputs:
#       app_version: ${{ steps.repo_data.outputs.app_version }}
    steps:
      - uses: actions/checkout@v2
      - name: print file
        run: |
          echo "sfdasdjflasjkfda
            asdf
            asdfasdfasd
            fa
            sdf
            asdf
            asdfadsfasdf 
            <b>adsfadsfasDF</b>
            " > test.txt
        
      - name: Comment PR with Plan
        uses: htec-infra/gha-utils/actions/comment-pr@0.3.2
        with:
          message: file::test.txt
#   auto_deploy:
#     name: Create GitHub Release
#     if: github.event.pull_request.merged == true  && contains(github.head_ref, 'release/')
#     needs: build_and_publish
#     runs-on: ubuntu-latest
#     steps:
#       - name: Run auto-deploy
#         uses: htec-infra/gha-utils/actions/repo-dispatch@feature/new-gh-release
#         with:
#           gh_token: ${{ secrets.CI_PAT }}
#           event_type: new_github_release
#           client_payload: '{"env": "dev", "version": "${{ needs.build_and_publish.outputs.app_version }}"}'
