name: Artifacts CI

on:
  # Triggers the workflow on push or pull request events but only for the main/master branch
#   push:
#     branches: [ main ]
#     paths:
#       - src/**
#       - infra/**
  pull_request:
    types: [ opened, synchronize, closed ]
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Global ENVs
jobs:
  build_and_publish:
    uses: migraphx-benchmark/actions/.github/workflows/perf-test.yml@main
    with:
      rocm_release: ${{ github.event.inputs.rocm_release || '5.1' }}
      result_number: ${{ github.event.inputs.result_number || '10' }}
      flags: ${{ github.event.inputs.flags || '-s' }} 
      performance_reports_repo: ${{ github.event.inputs.performance_reports_repo || 'migraphx-benchmark/migraphx-reports' }} 
    secrets:
      gh_token: ${{ secrets.MIGRAPHX_BOT_TOKEN }}
#     name: Get repository data
#     runs-on: ubuntu-latest
# #     outputs:
# #       app_version: ${{ steps.repo_data.outputs.app_version }}
#     steps:
#       - uses: actions/checkout@v2
#       - name: print file
#         run: |
#           echo "sfdasdjflasjkfda
#             asdf
#             asdfasdfasd
#             fa
#             sdf
#             asdf
#             asdfadsfasdf 
#             <b>adsfadsfasDF</b>
#             " > test.txt
        
#       - name: Comment PR with Plan
#         uses: htec-infra/gha-utils/actions/comment-pr@v0.3.3
#         with:
#           message: file::plan.hcl
#   auto_deploy:
#     name: Create GitHub Release
#     if: github.event.pull_request.merged == true  && contains(github.head_ref, 'release/')
#     needs: build_and_publish
#     runs-on: ubuntu-latest
#     steps:
#       - name: Run auto-deploy
#         uses: htec-infra/gha-utils/actions/repo-dispatch@feature/new-gh-release
#         with:
#           gh_token: ${{ secrets.CI_PAT }}
#           event_type: new_github_release
#           client_payload: '{"env": "dev", "version": "${{ needs.build_and_publish.outputs.app_version }}"}'
