name: GitHub Release
on:
  # Triggers the workflow on pull request close event, but only for the main branch
  repository_dispatch:
    types: [ new_github_release ]


jobs:
  publish:
      name: Publish
      runs-on: ubuntu-latest
      steps:
        - name: Create Release
          uses: htec-infra/gha-utils/actions/gh-release@main
