name: GitHub Release
on:
  # Triggers the workflow on pull request close event, but only for the main branch
  repository_dispatch:
    types: [ new_github_release ]


jobs:
  publish:
      name: Create Release >> ${{ github.event.client_payload.version }}
      runs-on: ubuntu-latest
      steps:
        - name: Run github-release action
          uses: htec-infra/gha-utils/actions/gh-release@main
          with:
            app_version: ${{ github.event.client_payload.version }} # optional
            app_revision:  ${{ github.event.client_payload.revision }} # optional
