name: GitHub Release
on:
  # Triggers the workflow on pull request close event, but only for the main branch
  repository_dispatch:
    types: [ new_github_release ]


jobs:
  publish:
      name: Publish
      runs-on: ubuntu-latest
      steps:
        - name: Create Release
          uses: htec-infra/gha-utils/actions/gh-release@feature/new-gh-release
          with:
            app_version: ${{ github.event.client_payload.version }}
            app_revision:  ${{ github.event.client_payload.revision || github.event.pull_request.head.sha }}
