name: GitHub Release Trigger and Wait
on:
  workflow_dispatch:

jobs:
  publish:
    name: Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Run auto-deploy
        uses: htec-infra/gha-utils/actions/slack@main
        with:
          slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
          message: "Test"
          msg_format: app-release
